# docker-compose.yml
version: '3.8'

services:
  server:
    build: ./server
    container_name: tcp_server
    networks:
      - socket-network
    ports:
      - "12345:12345"

  client:
    build: ./client
    container_name: tcp_client
    networks:
      - socket-network
    depends_on:
      - server

networks:
  socket-network:
    driver: bridge
